# Generated by Django 2.2.3 on 2020-05-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='简写标题'),
        ),
    ]
