# Generated by Django 2.2.3 on 2020-05-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text1', models.TextField(verbose_name='封面简介')),
                ('text2', models.TextField(verbose_name='博客简介')),
                ('text3', models.TextField(verbose_name='关于简介')),
                ('image1', models.ImageField(default='coverimage/zhixiang1.jpg', upload_to='coverimage/', verbose_name='封面图片')),
                ('image2', models.ImageField(default='coverimage/zhixiang2.jpg', upload_to='coverimage/', verbose_name='博客图片')),
                ('image3', models.ImageField(default='coverimage/zhixiang1.jpg', upload_to='coverimage/', verbose_name='关于图片')),
            ],
            options={
                'verbose_name': '个人简介',
                'verbose_name_plural': '个人简介',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='coverimage/default.jpg', upload_to='coverimage/%Y/%m/%d/', verbose_name='封面图片'),
        ),
    ]
